version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-srping-light-house
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: spring-light-house
      MARIADB_USER: lighthouse_user
      MARIADB_PASSWORD: lighthouse_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro

volumes:
  mariadb_data: